-- models/staging/stg_weather_forecast_7d.sql
select
    city as city_name,
    latitude,
    longitude,
    time as forecast_date,
    weather_code,
    temperature_2m_max as temp_max_celsius,
    temperature_2m_min as temp_min_celsius,
    apparent_temperature_max as apparent_temp_max_celsius,
    apparent_temperature_min as apparent_temp_min_celsius,
    sunrise,
    sunset,
    daylight_duration as daylight_duration_seconds,
    sunshine_duration as sunshine_duration_seconds,
    uv_index_max,
    uv_index_clear_sky_max,
    precipitation_sum as precipitation_mm,
    rain_sum as rain_mm,
    showers_sum as showers_mm,
    snowfall_sum as snowfall_cm,
    precipitation_hours,
    precipitation_probability_max as precipitation_probability_max_pct,
    wind_speed_10m_max as wind_speed_max_kmh,
    wind_gusts_10m_max as wind_gusts_max_kmh,
    wind_direction_10m_dominant as wind_direction_dominant_deg,
    shortwave_radiation_sum as shortwave_radiation_sum_mj_m2,
    et0_fao_evapotranspiration as et0_fao_evapotranspiration_mm
from {{ source('raw', 'weather_forecast_7d') }}
